### ISSUE TITLE
Error: spawn EAGAIN

### ISSUE THREAD

**Issue by pborreli** [IonicaBizau/repository-downloader#4]
Running the start command: 

```
info  Downloading all your repositories.
   >  Repository: pborreli/18f.gsa.gov
   >  Repository: pborreli/24pullrequests
   >  Repository: pborreli/42-protips-2014-conf
   >  Repository: pborreli/AB
   >  Repository: pborreli/accessible-html5-video-player
   >  Repository: pborreli/Adaptive-Images
   >  Repository: pborreli/addict
   >  Repository: pborreli/adept-jpg-compressor
   >  Repository: pborreli/admin-bundle
   >  Repository: pborreli/aidkit
   >  Repository: pborreli/airstream
   >  Repository: pborreli/alice
   >  Repository: pborreli/Amend
   >  Repository: pborreli/Anemometer
   >  Repository: pborreli/angular.js
   >  Repository: pborreli/anijs
   >  Repository: pborreli/annotations
   >  Repository: pborreli/annotations-1
   >  Repository: pborreli/ansible
   >  Repository: pborreli/ansible-modules-core
   >  Repository: pborreli/api-standards
   >  Repository: pborreli/app
   >  Repository: pborreli/arcanist
   >  Repository: pborreli/arrow
   >  Repository: pborreli/ArtBreadcrumbsBundle
   >  Repository: pborreli/ArteHateoasBundle
   >  Repository: pborreli/assert
   >  Repository: pborreli/assetic
   >  Repository: pborreli/assez-tic-de-perdre-du-temps-automatisez-conf
   >  Repository: pborreli/At.js
   >  Repository: pborreli/athletic
   >  Repository: pborreli/atom
   >  Repository: pborreli/atom-lint
   >  Repository: pborreli/atom-shell
   >  Repository: pborreli/atomic-site
   >  Repository: pborreli/atoum
   >  Repository: pborreli/Aura.Di
   >  Repository: pborreli/Aura.Filter
   >  Repository: pborreli/Aura.Framework
   >  Repository: pborreli/Aura.Http
   >  Repository: pborreli/Aura.Intl
   >  Repository: pborreli/Aura.Marshal
   >  Repository: pborreli/Aura.Sql
   >  Repository: pborreli/Aura.View
   >  Repository: pborreli/Aura.Web
   >  Repository: pborreli/auraphp.github.com
   >  Repository: pborreli/AutoLogin
   >  Repository: pborreli/automating-workflow-ticonf2014-talk
   >  Repository: pborreli/awesome-symfony2
   >  Repository: pborreli/aws-sdk-php
   >  Repository: pborreli/AzureDistributionBundle
   >  Repository: pborreli/backbone-events-standalone
   >  Repository: pborreli/backup-manager
   >  Repository: pborreli/BadFaith
   >  Repository: pborreli/badge-poser
   >  Repository: pborreli/barcha.github.com
   >  Repository: pborreli/barometre
   >  Repository: pborreli/bashblog
   >  Repository: pborreli/BazingaFakerBundle
   >  Repository: pborreli/BazingaGeocoderBundle
   >  Repository: pborreli/Behat
   >  Repository: pborreli/behatch-contexts
   >  Repository: pborreli/BehatPageObjectExtension
   >  Repository: pborreli/behind-github-geojson
   >  Repository: pborreli/benbalter.github.com
   >  Repository: pborreli/bernard
   >  Repository: pborreli/BeSimpleSsoAuthBundle
   >  Repository: pborreli/best-bundle-conf
   >  Repository: pborreli/biscotto
   >  Repository: pborreli/blog
   >  Repository: pborreli/blog-1
   >  Repository: pborreli/blog-2
   >  Repository: pborreli/blog_liip_ch_posts
   >  Repository: pborreli/bodaclick.github.com
   >  Repository: pborreli/bolt
   >  Repository: pborreli/Book-of-Speed
   >  Repository: pborreli/boom
   >  Repository: pborreli/bootstrap
   >  Repository: pborreli/boris
   >  Repository: pborreli/bower
   >  Repository: pborreli/Box
   >  Repository: pborreli/breach_core
   >  Repository: pborreli/broker
   >  Repository: pborreli/browser-diet
   >  Repository: pborreli/buffer-blog-v2
   >  Repository: pborreli/buffer-bot
   >  Repository: pborreli/buffer-chrome
   >  Repository: pborreli/buffer-extension-shared
   >  Repository: pborreli/bufferbot-slack
   >  Repository: pborreli/burn
   >  Repository: pborreli/Buzz
   >  Repository: pborreli/bxslider-4
   >  Repository: pborreli/c4
   >  Repository: pborreli/ca-marche-chez-moi
   >  Repository: pborreli/cache
   >  Repository: pborreli/cache-1
   >  Repository: pborreli/cada
   >  Repository: pborreli/cadvisor
   >  Repository: pborreli/Cakebrew
   >  Repository: pborreli/cakephp
   >  Repository: pborreli/Carbon
   >  Repository: pborreli/carte
   >  Repository: pborreli/cartographer
   >  Repository: pborreli/casperjs
   >  Repository: pborreli/chad.github.io
   >  Repository: pborreli/chancejs
   >  Repository: pborreli/Chart.js
   >  Repository: pborreli/cheddar-mac
   >  Repository: pborreli/choosealicense.com
   >  Repository: pborreli/chute
   >  Repository: pborreli/ClassPreloader
   >  Repository: pborreli/climate
   >  Repository: pborreli/clockwork
   >  Repository: pborreli/cmf-sandbox
   >  Repository: pborreli/Codeception
   >  Repository: pborreli/coding-standard
   >  Repository: pborreli/colada
   >  Repository: pborreli/collections
   >  Repository: pborreli/CommentsBundle
   >  Repository: pborreli/common
   >  Repository: pborreli/Common-1
   >  Repository: pborreli/common-documentation
   >  Repository: pborreli/composer
   >  Repository: pborreli/composer-service
   >  Repository: pborreli/connect
   >  Repository: pborreli/ControllerUtil
   >  Repository: pborreli/CoopTilleulsCKEditorSonataMediaBundle
   >  Repository: pborreli/coreclr
   >  Repository: pborreli/crm
   >  Repository: pborreli/cron-expression
   >  Repository: pborreli/CrowdinBundle
   >  Repository: pborreli/csv
   >  Repository: pborreli/customelements.io
   >  Repository: pborreli/damnit
   >  Repository: pborreli/data-fixtures
   >  Repository: pborreli/database
   >  Repository: pborreli/datagov-design
   >  Repository: pborreli/datum
   >  Repository: pborreli/dbal
   >  Repository: pborreli/DeadDropDocs
   >  Repository: pborreli/deep_thought
   >  Repository: pborreli/DenetmenBundle
   >  Repository: pborreli/dev-human
   >  Repository: pborreli/devdocs
   >  Repository: pborreli/developer.github.com
   >  Repository: pborreli/dflydev-markdown
   >  Repository: pborreli/diggdigg
   >  Repository: pborreli/discussion
   >  Repository: pborreli/django-project-template
   >  Repository: pborreli/django-rest-framework
   >  Repository: pborreli/doc.php
   >  Repository: pborreli/docker
   >  Repository: pborreli/docker-php
   >  Repository: pborreli/docs
   >  Repository: pborreli/docs-1
   >  Repository: pborreli/docs-2
   >  Repository: pborreli/docs-3
   >  Repository: pborreli/docs-4
   >  Repository: pborreli/docs-5
   >  Repository: pborreli/docs.drone.io
   >  Repository: pborreli/doctrine-extra-bundle
   >  Repository: pborreli/doctrine2
   >  Repository: pborreli/DoctrineCacheBundle
   >  Repository: pborreli/DoctrineExtensions
   >  Repository: pborreli/DoctrineModule
   >  Repository: pborreli/DoctrineMongoDBBundle
   >  Repository: pborreli/DoctrinePHPCRBundle
   >  Repository: pborreli/documentation
   >  Repository: pborreli/documentation-1
   >  Repository: pborreli/documentation-2
   >  Repository: pborreli/documentation-3
   >  Repository: pborreli/dogpatch
   >  Repository: pborreli/dotnet
   >  Repository: pborreli/drest
   >  Repository: pborreli/drgomesp.github.com
   >  Repository: pborreli/dropzone
   >  Repository: pborreli/duo
   >  Repository: pborreli/EasyAdminBundle
   >  Repository: pborreli/ecommerce
   >  Repository: pborreli/editor
   >  Repository: pborreli/EkinoNewRelicBundle
   >  Repository: pborreli/ElaoFormTranslationBundle
   >  Repository: pborreli/elastica-conf
   >  Repository: pborreli/elasticsearch
   >  Repository: pborreli/elasticsearch-bundle
   >  Repository: pborreli/elasticsearch-php
   >  Repository: pborreli/elcaro
   >  Repository: pborreli/elcodi
   >  Repository: pborreli/elcodi-blog
   >  Repository: pborreli/elcodi-docs
   >  Repository: pborreli/elephant
   >  Repository: pborreli/email-test
   >  Repository: pborreli/EmailReplyParser
   >  Repository: pborreli/emailvision
   >  Repository: pborreli/en-docs.behat.org
   >  Repository: pborreli/en-mink.behat.org
   >  Repository: pborreli/end-to-end
   >  Repository: pborreli/endcredits
   >  Repository: pborreli/EntityAudit
   >  Repository: pborreli/envoy
   >  Repository: pborreli/exporter
   >  Repository: pborreli/ezforms-bundle
   >  Repository: pborreli/ezpublish-kernel
   >  Repository: pborreli/ezpublish-legacy
   >  Repository: pborreli/ezpublish-legacy-extension-installer
   >  Repository: pborreli/ezpublish-migrations-bundle
   >  Repository: pborreli/ezpublish5
   >  Repository: pborreli/ezpublish5-and-symfony2
   >  Repository: pborreli/eZPublishProxyConnect
   >  Repository: pborreli/f43.me
   >  Repository: pborreli/fail2ban
   >  Repository: pborreli/Faker
   >  Repository: pborreli/fatfree
   >  Repository: pborreli/feedback
   >  Repository: pborreli/FeedBundle
   >  Repository: pborreli/fenom
   >  Repository: pborreli/fig-standards
   >  Repository: pborreli/Finite
   >  Repository: pborreli/firing-range
   >  Repository: pborreli/fixthatcode.com
   >  Repository: pborreli/flickholdr
   >  Repository: pborreli/flight
   >  Repository: pborreli/flight-1
   >  Repository: pborreli/flow
   >  Repository: pborreli/flux
   >  Repository: pborreli/Flysystem
   >  Repository: pborreli/fnordmetric
   >  Repository: pborreli/forceutf8
   >  Repository: pborreli/forkcms
   >  Repository: pborreli/Form
   >  Repository: pborreli/fortyfour
   >  Repository: pborreli/FOSHttpCacheBundle
   >  Repository: pborreli/FOSMessageBundle
   >  Repository: pborreli/FOSRestBundle
   >  Repository: pborreli/FOSUserBundle
   >  Repository: pborreli/foundation
   >  Repository: pborreli/fractal
   >  Repository: pborreli/framework
   >  Repository: pborreli/framework-1
   >  Repository: pborreli/french-tech-hall-of-fame
   >  Repository: pborreli/Front-end-Developer-Interview-Questions
   >  Repository: pborreli/FullHackerNews
   >  Repository: pborreli/fzaninotto.github.com
   >  Repository: pborreli/gaspaio.github.com
   >  Repository: pborreli/gaudi
   >  Repository: pborreli/Gaufrette
   >  Repository: pborreli/geekweek12
   >  Repository: pborreli/generator-joli-symfony
   >  Repository: pborreli/genghis
   >  Repository: pborreli/GeocodableBehavior
   >  Repository: pborreli/Geocoder
   >  Repository: pborreli/geocoder-silex
   >  Repository: pborreli/geojson
   >  Repository: pborreli/geojson-diff
   >  Repository: pborreli/GeonamesServer
   >  Repository: pborreli/GeonamesServer-1
   >  Repository: pborreli/Geotools
   >  Repository: pborreli/gh-downloader
   >  Repository: pborreli/Ghost
   >  Repository: pborreli/git-internals-pdf
   >  Repository: pborreli/gitbook
   >  Repository: pborreli/github-todos
   >  Repository: pborreli/GithubTeamReviewer
   >  Repository: pborreli/githut
   >  Repository: pborreli/gitlist
   >  Repository: pborreli/gitonomy

Error: spawn EAGAIN
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at exports.exec (child_process.js:591:18)
    at Gry.exec (/Users/pborreli/Contrib/repository-downloader/node_modules/gry/lib/index.js:33:5)
    at /Users/pborreli/Contrib/repository-downloader/github.js:187:18
    at /Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:570:21
    at /Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:249:17
    at /Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:125:13
info  Getting the organizations you belong to.

**Comment by IonicaBizau** [comment]
Looks like there are too many processes (`git clone ...`). Gonna take a look on this in the next days.

**Comment by pborreli** [comment]
thanks @IonicaBizau !

**Comment by IonicaBizau** [comment]
I'm on it, solving it via: https://github.com/IonicaBizau/node-limit-it

**Comment by pborreli** [comment]
haha great !

**Comment by IonicaBizau** [comment]
Actually using  [exec-limiter](https://github.com/IonicaBizau/node-exec-limiter), integrated into [gry](https://github.com/IonicaBizau/node-gry), via https://github.com/IonicaBizau/node-gry/pull/2.
