### ISSUE TITLE
TypeError: Cannot read property 'full_name' of undefined

### ISSUE THREAD

**Issue by pborreli** [IonicaBizau/repository-downloader#9]
```
  >  Repository: pborreli/_s

TypeError: Cannot read property 'full_name' of undefined
    at /Users/pborreli/Contrib/repository-downloader/github.js:178:37
    at /Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:570:21
    at /Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:249:17
    at /Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:46:24)
    at async.each (/Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:248:13)
    at Object.map (/Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:219:23)
    at _parallel (/Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:568:20)

**Comment by IonicaBizau** [comment]
OK, so let's debug it: put [here](https://github.com/IonicaBizau/repository-downloader/blob/6726f0c108b64a661230a2e1bf5481c063697749/github.js#L177) the following code:

```js
if (!c) {
   console.log(repos);
   return callback();
}
```

**Comment by IonicaBizau** [comment]
Actually, put it with [two lines upper](https://github.com/IonicaBizau/repository-downloader/blob/6726f0c108b64a661230a2e1bf5481c063697749/github.js#L175).

**Comment by pborreli** [comment]
Hmm i don't get it maybe you will :smile: 

It doesn't crash with those lines added
```
  >  Repository: pborreli/_s
   >  Page: 2
info  Getting the repositories where htty created pull requests.
   >  Page: 1
   >  Downloaded pborreli/ArtBreadcrumbsBundle (1/735)
info  Downloading htty's repositories.
   >  Repository: htty/htty
   >  Repository: htty/htty.github.com
   >  Downloaded pborreli/AB (2/735)
   >  Downloaded pborreli/Adaptive-Images (3/735)

**Comment by IonicaBizau** [comment]
Hahaha! Make sure you removed the downloads (`bitbucket` and `github`). :smile:

**Comment by pborreli** [comment]
just did, relaunched start, no more crash :dizzy_face:

**Comment by IonicaBizau** [comment]
Maybe... it's because of the basic auth rate limit (up to 5000 requests / hour). I will try to reproduce it.

**Comment by pborreli** [comment]
still running : 266/735

**Comment by IonicaBizau** [comment]
I have 4 instances of repository-downloader, all of them downloading things:

```sh
$ ps aux | grep 'git clone' | wc -l
353
```

The issue is not about downloading repositories but making requests to GitHub API.

**Comment by pborreli** [comment]
yes understood, if it reproduce I will inform you

**Comment by IonicaBizau** [comment]
Hopefully it worked fine. :smile:
